In [116]:
import pandas as pd
import numpy as np

In [117]:
df = pd.read_excel('Telco_customer_churnG3.xlsx')
df

,CustomerID,State,City,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,California,Los Angeles,"33.964131, -118.272783",33.964131,-118.272783,Male,No,No,No,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,California,Los Angeles,"34.059281, -118.30742",34.059281,-118.307420,Female,No,No,Yes,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,California,Los Angeles,"34.048013, -118.293953",34.048013,-118.293953,Female,No,No,Yes,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,7892-POOKP,California,Los Angeles,"34.062125, -118.315709",34.062125,-118.315709,Female,No,Yes,Yes,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,California,Los Angeles,"34.039224, -118.266293",34.039224,-118.266293,Male,No,No,Yes,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,California,Landers,"34.341737, -116.539416",34.341737,-116.539416,Female,No,No,No,...,Two year,Yes,Bank transfer (automatic),21.15,1419.40,No,0,45,5306,NaN
7039,6840-RESVB,California,Adelanto,"34.667815, -117.536183",34.667815,-117.536183,Male,No,Yes,Yes,...,One year,Yes,Mailed check,84.80,1990.50,No,0,59,2140,NaN
7040,2234-XADUH,California,Amboy,"34.559882, -115.637164",34.559882,-115.637164,Female,No,Yes,Yes,...,One year,Yes,Credit card (automatic),103.20,7362.90,No,0,71,5560,NaN
7041,4801-JZAZL,California,Angelus Oaks,"34.1678, -116.86433",34.167800,-116.864330,Female,No,Yes,Yes,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,California,Apple Valley,"34.424926, -117.184503",34.424926,-117.184503,Male,No,No,No,...,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,0,38,5097,NaN

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   State              7043 non-null   object
 2   City               7043 non-null   object
 3   Lat Long           7043 non-null   object
 4   Latitude           7043 non-null   float64
 5   Longitude          7043 non-null   float64
 6   Gender             7043 non-null   object
 7   Senior Citizen     7043 non-null   object
 8   Partner            7043 non-null   object
 9   Dependents         7043 non-null   object
 10  Tenure Months      7043 non-null   int64
 11  Phone Service      7043 non-null   object
 12  Multiple Lines     7043 non-null   object
 13  Internet Service   7043 non-null   object
 14  Online Security    7043 non-null   object
 15  Online Backup      7043 non-null   object
 16  Device Protection  7043 non-null   object
 17  Tech Support       7043 non-null   object
 18  Streaming TV       7043 non-null   object
 19  Streaming Movies   7043 non-null   object
 20  Contract           7043 non-null   object
 21  Paperless Billing  7043 non-null   object
 22  Payment Method     7043 non-null   object
 23  Monthly Charges    7043 non-null   float64
 24  Total Charges      7032 non-null   float64
 25  Churn Label        7043 non-null   object
 26  Churn Value        7043 non-null   int64
 27  Churn Score        7043 non-null   int64
 28  CLTV               7043 non-null   int64
 29  Churn Reason       1869 non-null   object
dtypes: float64(4), int64(4), object(22)
memory usage: 1.6+ MB

In [119]:
df.isna().sum()

CustomerID              0
State                   0
City                    0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges          11
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

# Handing missing values

In [120]:
df.loc[df['Total Charges'].isna(), ['Tenure Months', 'Total Charges']]

      Tenure Months  Total Charges
2234              0            NaN
2438              0            NaN
2568              0            NaN
2667              0            NaN
2856              0            NaN
4331              0            NaN
4687              0            NaN
5104              0            NaN
5719              0            NaN
6772              0            NaN
6840              0            NaN

In [121]:
# Handling missing values

In [122]:
df['Total Charges'] = df['Total Charges'].fillna(0)

# Grouping data into feature(x) and target(y)

In [123]:
# Our feature data consist of categorical and numerical columns
cat_col = ['Internet Service','Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 
          'Payment Method', 'Contract', 'Senior Citizen']

num_col = ['Tenure Months', 'Monthly Charges', 'Total Charges']

x = df[cat_col + num_col]
y = df['Churn Value']

# Train, Test, Split

In [124]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.20, random_state = 42, stratify = y)

#  Encoding

In [125]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

processor = ColumnTransformer( transformers = [('num', StandardScaler(), num_col),
                                ('cat', OneHotEncoder(drop = 'first', sparse_output = False), cat_col)] )

# p_xtrain = processed xtrain
# p_xtest = processed xtest

p_xtrain = processor.fit_transform(x_train)
p_xtest = processor.transform(x_test)


Buiiding Models

# LogisticRegression

In [126]:
from sklearn.linear_model import LogisticRegression

# m1 = model 1
# creating m1 object from class LogisticRegression

m1 = LogisticRegression(max_iter = 1000,class_weight = 'balanced', random_state = 42)
# training the model
m1.fit(p_xtrain, y_train)

#  The model has learnt so its time to test it

test1 = m1.predict(p_xtest)

In [137]:
# Metrics to evaluate the performance of the model

from sklearn.metrics import classification_report, confusion_matrix

m1_clreport = classification_report(y_test,test1)
m1_cfmatrix = confusion_matrix(y_test, test1)

print(' --- Classification Report ---')
print(m1_clreport)
print(' --- Confusion Matrix --- ')
print(m1_cfmatrix)

 --- Classification Report ---
              precision    recall  f1-score   support

           0       0.91      0.71      0.80      1035
           1       0.50      0.80      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.80      0.74      0.75      1409

 --- Confusion Matrix ---
[[737 298]
 [ 74 300]]

# Random Forest

In [156]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier 

m2 = RandomForestClassifier(n_estimators = 100, class_weight = 'balanced', random_state = 42)
m2.fit(p_xtrain, y_train)
test2 = m2.predict(p_xtest)

In [157]:
m2_clreport = classification_report(y_test, test2)
m2_cfmatrix = confusion_matrix(y_test, test2)

print(' --- Random Forest(RF) Classification Report ---')
print(m2_clreport)
print(' --- RF Confusion Matrix --- ')
print(m2_cfmatrix)

 --- Random Forest(RF) Classification Report ---
              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1035
           1       0.62      0.46      0.53       374

    accuracy                           0.78      1409
   macro avg       0.72      0.68      0.69      1409
weighted avg       0.77      0.78      0.77      1409

 --- RF Confusion Matrix ---
[[931 104]
 [202 172]]

#  GradientBoosting

In [160]:
m3 = GradientBoostingClassifier(n_estimators = 100, learning_rate = 0.1, random_state = 42)
m3.fit(p_xtrain, y_train)
test3 = m3.predict(p_xtest)

In [161]:
m3_clreport = classification_report(y_test, test3)
m3_cfmatrix = confusion_matrix(y_test, test3)

print(' --- Gradient Boosting(GB) Classification Report ---')
print(m3_clreport)
print(' --- GB Confusion Matrix --- ')
print(m3_cfmatrix)

 --- Gradient Boosting(GB) Classification Report ---
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1035
           1       0.65      0.52      0.58       374

    accuracy                           0.80      1409
   macro avg       0.74      0.71      0.72      1409
weighted avg       0.79      0.80      0.79      1409

 --- GB Confusion Matrix ---
[[931 104]
 [181 193]]